[project]
name = "python-plotting"
version = "0.1.0"
description = "Single pipeline Yamal-Europe case plotting scripts"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "logging>=0.4.9.6",
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
    "pathlib>=1.0.1",
]
